name: iOS starter workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  PROJECT: ${{ 'BullsEye.xcworkspace' }}
  SCHEME: ${{ 'BullsEye' }}

jobs:
  build-and-test:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    env:
      PLATFORM: ${{ 'iOS Simulator' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Display XCode Path for debug
        run: |
          xcode-select -p  
      - name: Build For Testing
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild \
          -workspace $PROJECT \
          -scheme $SCHEME \
          -sdk iphonesimulator \
          -destination "platform=$PLATFORM,name=$device" \
          build-for-testing
      - name: Test
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild \
          -workspace $PROJECT \
          -scheme $SCHEME \
          -sdk iphonesimulator \
          -destination "platform=$PLATFORM,name=$device" \
          test-without-building

  archive-and-deploy:
    name: Archive and Deploy to Testflight
    needs: [build-and-test]
    runs-on: macos-latest
    env:
       DATA_DIR: ${{ 'xcbuild' }}
       ARCHIVE_NAME:  ${{ 'BullsEye.xcarchive' }}
       EXPORT_DIR: ${{ 'export' }}
       IPA_NAME: ${{ 'BullsEye.ipa' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Display XCode Path for debug
        run: |
          xcode-select -p  
      # from https://docs.github.com/en/enterprise-cloud@latest/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles    
      - name: Install the App Store Connect API Auth Key
        env: 
          APP_STORE_CONNECT_BASE64: ${{ secrets.APP_STORE_CONNECT_API_BASE_64 }}
          APP_STORE_KEY: ${{ secrets.APPSTORE_API_KEY_ID }}
        run: |
          # extract App Store secret to p8 file. Needs to be in one of ~/private_keys', '~/.private_keys', '~/.appstoreconnect/private_keys, /path/to/project/private_keys
          FILE_NAME=AuthKey_${APP_STORE_KEY}.p8
          mkdir -p private_keys
          echo -n "$APP_STORE_CONNECT_BASE64" | base64 --decode --output private_keys/${FILE_NAME}
      - name: Increment Build No.
        env:
          BUILD_NO: ${{ github.run_number }}
        run: |
          # Set Buiild Number. Not worrying about storing to repo.
          agvtool new-version -all ${BUILD_NO}
      - name: Build For Release
        run: |
          xcodebuild \
          -workspace $PROJECT \
          -scheme $SCHEME \
          -configuration Release \
          -sdk iphoneos \
          -derivedDataPath $DATA_DIR \
          -archivePath ${DATA_DIR}/${ARCHIVE_NAME} \
          archive
      - name: Export Archive 
        run: |
          xcodebuild \
          -exportArchive \
          -archivePath ${DATA_DIR}/${ARCHIVE_NAME} \
          -exportPath $EXPORT_DIR \
          -exportOptionsPlist exportOptions.plist \
          -verbose
      - name: Upload to app store
        env:
          APP_STORE_KEY: ${{ secrets.APPSTORE_API_KEY_ID }}
          APPSTORE_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        run: |
          xcrun altool --validate-app -f ${EXPORT_DIR}/${IPA_NAME} -t ios --apiKey $APP_STORE_KEY --apiIssuer $APPSTORE_ID

          xcrun altool --upload-app -f ${EXPORT_DIR}/${IPA_NAME} -t ios --apiKey $APP_STORE_KEY --apiIssuer $APPSTORE_ID --verbose

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: release
          path: ${{ env.EXPORT_DIR }}
          retention-days: 5
         
     
